### ISSUE TITLE
Make hand writing possible ?

### ISSUE THREAD

**Issue by deb75** [misohena/el-easydraw#18]
Is it planned in the future to introduce hand writing ?

I have tried with a touchscreen laptop and its pen.

It works well, except that it only draws on the grid points.

Is it possible to tweak the grid size ? with a much greater
number of points so that hand writing could give a decent appearance ?

Regards

**Comment by misohena** [comment]
(Translated Message)
You can disable the grid by selecting Main Menu>View>Grid or by pressing the # key. You can also change the grid size by selecting Main Menu>View>Set Grid Interval...

It seems that there are people using pen devices. Reference: #9 #17

(Original Message)
メインメニュー>View>Gridを選択または#キーでグリッドを無効に出来ます。また、メインメニュー>View>Set Grid Interval...を選択でグリッドのサイズを変更できます。

ペンデバイスを使っている人はいるようです。参考: #9 #17

**Comment by deb75** [comment]
Thanks,

Just a last question, I digged into `edraw` settings and could not find how to set the width of line (like the pen width)

How can I set the width of line to something thinner ?

Regards

**Comment by misohena** [comment]
(Translated Message)
The width of line is specified by the stroke-width property of path element.

To specify the line width just before drawing a line, for example, if you are using the handwriting tool, click the button at the bottom of the toolbar. A list of default properties will be displayed. Change the stroke-width (default is 4) to the value you like (you can also change it by turning the wheel or dragging on the label). If you then draw a line, it will be displayed at that width.

To change the width of a line you have already drawn, right-click on the line and select "Properties..." (or type s, click on the line, p, p). A list of properties for that line will be displayed, so change the stroke-width.

To specify the default values when you open the editor, change the edraw-default-shape-properties variable. For example, in init.el:

```
(with-eval-after-load "edraw"
   (setf (alist-get 'stroke (alist-get 'path edraw-default-shape-properties)) "#222")
   (setf (alist-get 'stroke-width (alist-get 'path edraw-default-shape-properties)) 2))
```

This may seem like a strange method, but this is because there are many areas where the specifications have not yet been determined. The method for specifying initial values for shapes may change in the future. I'm currently thinking about issues such as separation of user default values, default values for each tool rather than for each shape type, and batch switching and saving of presets (sets of default values). Even if the specifications change, I will try to maintain the above settings as much as possible.

(Original Message)
線の幅はpath要素のstroke-widthプロパティで指定します。

線の幅を線を描く直前に指定するには、例えば手書きツールであればツールバーの一番下のボタンをクリックしてください。デフォルトのプロパティ一覧が表示されます。その中のstroke-width(デフォルトは4)を好きな値に変更してください(ラベル上でホイールを回したり、ドラッグすることでも変更できます)。その後線を引くと、その幅で表示されます。

既に描いた線の幅を変えるには、線を右クリックして「Properties...」を選択してください(または s, 線をクリック, p, p)。その線のプロパティ一覧が表示されるので、stroke-widthを変更してください。

エディタを開いた時点のデフォルト値を指定するには、 edraw-default-shape-properties変数を変更します。例えばinit.elで次のようにします。

```
(with-eval-after-load "edraw"
  (setf (alist-get 'stroke (alist-get 'path edraw-default-shape-properties)) "#222")
  (setf (alist-get 'stroke-width (alist-get 'path edraw-default-shape-properties)) 2))
```

奇妙な方法だと思われるかもしれませんが、この辺りの仕様決まっていない部分が多々あるからです。図形の初期値を指定する方法については、将来的に変更する可能性があります。ユーザー既定値の分離、図形種類毎では無いツール毎の既定値、プリセット(既定値集合)の一括切り替え・保存といった問題について考えているところです。仕様が変わったとしても、上記の設定ができるだけ維持されるように努めるつもりです。

**Comment by misohena** [comment]
(Translated Message)
There seem to be no other questions, so I'll close the issue.

In addition, with recent changes, you can also set the "default property the next time you start editing" by selecting Property Editor -> Preset -> Special Preset -> Save as Initial Path Shape Default.

(Original Message)
他に質問は無いようなのでIssueを閉じます。

なお最近の変更によって、 Property Editor -> Preset -> Special Preset -> Save as Initial Path Shape Default と選択することでも、「次回編集を開始したときのデフォルトプロパティ」を設定できるようになりました。

**Comment by nasseralkmim** [comment]
Hi misohena, I noticed that after drawing a few lines the number of points is very large and the drawing process becomes sluggish. Is there an easy solution for adding a tolerances, and a non-agressive smoothing process, similar to inkscape. Maybe this has some ideas: [https://gitlab.com/inkscape/inkscape/-/blob/master/src/ui/tools/pencil-tool.cpp?ref_type=heads](url)

**Comment by misohena** [comment]
@nasseralkmim 
(Translated Message)
Hi nasseralkmim.
I don't notice any sluggishness after just drawing a few lines, so I don't really understand the situation. Could you please tell me the details of the situation?
What is your environment like?
After what line is drawn, when and how does it slow down?
If the smoothing feature is enabled (default), I don't think the number of points generated will be that large. Have you disabled the smoothing function?

(Original Message)
nasseralkmimさんこんにちは。
私は数本の線を描いたくらいでは動作の鈍さを感じないので、状況がよく分かりません。詳しい状況を教えて頂けないでしょうか。
お使いの環境はどのようなものでしょうか。
どのような線を引いた後、どのタイミングでどのように動作が鈍くなりますか？
スムージング機能が有効になっている場合(デフォルト)、生成される点の数はそれほど多くはならないと思います。スムージング機能を無効化していますか？

**Comment by nasseralkmim** [comment]
Yes, the smoothing is disabled to allow handwritten notes with more details. One workaround I found is to toggle the smoothing method between "nil" and "bezier-fitting" if I want to draw a shape or text.

**Comment by misohena** [comment]
@nasseralkmim 
(Translated Message by Chat-GPT)
Oh, you’re the one who wrote #17. My apologies for the long wait.

I’ve made some modifications in commit https://github.com/misohena/el-easydraw/commit/dba6c4ebbdb72c06f52373fc8bae1ce0e0c9ea44. The changes aim to improve the behavior when edraw-editor-tool-freehand-smoothing-method is set to bezier-fitting.

Previously, there was an issue with bezier-fitting where corners would become rounded off. To address this, I implemented a pre-corner detection method to prevent bezier-fitting at those points.

I also added two customization variables for detecting corners:

- edraw-editor-tool-freehand--bezier-fitting-corner-angle-min
- edraw-editor-tool-freehand--bezier-fitting-corner-distance-min

Additionally, I made the bezier-fitting tolerance customizable instead of fixed at 2.0, and changed the default value to 1.0:

- edraw-editor-tool-freehand-bezier-fitting-tolerance

While this might not completely solve the problem, please give it a try and let me know how it works for you.

(Original Message)
おっと、 #17 を書いた人ですね。失礼しました。長いことお待たせしてすみません。

コミット https://github.com/misohena/el-easydraw/commit/dba6c4ebbdb72c06f52373fc8bae1ce0e0c9ea44 で少し修正してみました。修正は edraw-editor-tool-freehand-smoothing-method が bezier-fitting の時の動作を改善するものです。

bezier-fittingはコーナーがなまってしまうという問題がありましたが、事前にコーナーを検出して、そこにはベジェフィッティングをしないようにしました。

コーナーと検出するための閾値として二つのカスタマイズ変数を追加しました:
- edraw-editor-tool-freehand--bezier-fitting-corner-angle-min
- edraw-editor-tool-freehand--bezier-fitting-corner-distance-min

また、ベジェフィッティングの許容値が以前は2.0固定だったのをカスタマイズ可能にして、かつ、デフォルト値を1.0へ変更しました:
- edraw-editor-tool-freehand-bezier-fitting-tolerance

どこまでいっても完全には解決しないと思いますが、是非試してみてどうだったか教えてください。

**Comment by nasseralkmim** [comment]
It is a real improvement! Well done! Thanks for the update.
