### ISSUE TITLE
Release to melpa?

### ISSUE THREAD

**Issue by seagle0128** [misohena/el-easydraw#2]
Thank you for the amazing project! I am wondering whether it will be released to melpa. It would be better to publish there for more visibilities.

**Comment by misohena** [comment]
seagle0128さんこんにちは。お褒め頂きありがとうございます。

MELPAへの登録についてですが、私は考えておりません。

一に、私は英語がとても苦手で登録にまつわる英語でのコミュニケーションにとても耐えられません。私が書いているのは英語に似た何かですし、英語を読むのもとても時間がかかります。私の中学時代の英語の成績は常に5段階中2でした。まわりに英語が出来る人はおらず、書いたものを確認することも出来ません。

第二に、私はコードの細かいどうでもよい部分に文句を言われるのが好きではありません。MELPAには厳格なレビュープロセスがあると聞いたことがあります。以前に他のプロジェクトでMELPAに登録するためにコメントや括弧の位置等を直せと言ってきた人がいたのですが、私が断るとその人は「コードはGPLだから私がフォークしても良いですよね？」と言ってきました。その後、彼はプロジェクトを引き取りましたとアナウンスしていました。それ以来私はMELPAに対する興味を失っています。

本プロジェクトはGPLですので、コードは好きなように使って頂いて構いません。フォークしてMELPAに登録するもよし、有用な一部分だけコピーするもよし。それによってEmacsに沢山の有用なパッケージが増えるのなら私としても嬉しい限りです。

Google Translate:

Hello seagle0128. Thank you for your compliment.

Regarding registration with MELPA, I am not thinking about it.

First, I'm not very good at English and I can't stand the communication in English related to registration. I'm writing something similar to English, and reading English takes a lot of time. My English grade in middle school was always 2 out of 5. There are no people around me who can speak English, and I can't even check what I wrote.

Second, I don't like being complained about the small, trivial parts of the code. I've heard that MELPA has a rigorous review process. Previously, there was a person who asked me to correct the position of comments and parentheses in order to register with MELPA in other projects, but when I refused, that person said, "The code is GPL, so I can fork it. Isn't it? " After that, he announced that he had taken over the project. Since then I have lost interest in MELPA.

This project is GPL, so you can use the code as you like. You can fork and register with MELPA, or you can copy only useful parts. I would be happy if that would add a lot of useful packages to Emacs.

**Comment by seagle0128** [comment]
Understand. Please let me know if I can help on it. Let's focus on the project for now. Thanks!
